- scripts/ddetailer.py
* checkpoint, clip skip, vae and sampler override settings are added
> more advanced options added

- scripts/ddetailer.py
add an inpaint helper to test detailer easily
> Inpainting

- config/default_runtime.py
- config/face_yolov8n.py
- config/face_yolov8s.py
- config/hand_yolov8n.py
- config/hand_yolov8s.py
- config/yolov8_s_syncbn_fast_8xb16-500e_coco.py
- scripts/ddetailer.py
mmyolo added to support @Bingsu 's yolov8 models
- original yolov8  models https://huggingface.co/Bingsu/adetailer
- converted models https://huggingface.co/wkpark/mmyolo-yolov8
> mmyolo added

- scripts/ddetailer.py
* always output preview/masks to the default outpath
* fix dir separator
* auto search modelname
> Rebrand to Mu DDetailer

- scripts/ddetailer.py
read meta classes from the given model file correctly.
> read meta classes

- scripts/ddetailer.py
- scripts/mediapipe.py
> support mediapipe

- scripts/ddetailer.py
- sampler_name
- `p.setup_prompts()` is a newly added procedure
- filename path has `?timestamp`
- cleanup legacy compatible codes (for older version of mmcv / mmdet)
> fix compatible issues

- javascript/ui.js
- scripts/ddetailer.py
support partial update gallery while using the inpainting helper
> support partial update gallery

- scripts/ddetailer.py
> Detector fix

- scripts/ddetailer.py
* fix re_param_code
* fix for empty generation_info case
> misc fixes

- scripts/ddetailer.py
* support import pnginfo from the inpainting helper
> import prompt from inpainting helper

- javascript/ui.js
- scripts/ddetailer.py
- scripts/mediapipe.py
> support selectable masks/segms

- javascript/ui.js
- scripts/ddetailer.py
- scripts/mediapipe.py
> save detection results to infotexts

- scripts/ddetailer.py
- scripts/ultralytics.py
- MMDET is highly configurable, but has a relatively slow development status.
- mediapipe is very fast, but less accurate.
- ultralytics is under active development status, but less configurable.
now all three of them are supported!
> support ultralytics

- scripts/ddetailer.py
> support nsfw-censor

- scripts/ddetailer.py
* with backward compatibile check
> use sha256 instead old model_hash

- scripts/ddetailer.py
overwrite params.txt after `process_image()` to preserve original prompt
> write params.txt

- cn_module.py
- scripts/ddetailer.py
> Controlnet support

- install.py
- scripts/ddetailer.py
> extract install.py and update

- install.py
suggested by @w-e-w https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/235
Thank you!
> reduce loading time using importlib.metadata

- cn_module.py
- scripts/ddetailer.py
* support ResizeMode
* misc bugs fixed
* translate ResizeMode, ControlMode correctly
> add ResizeMode(), misc update/bug fixes

- scripts/ddetailer.py
- scripts/detectors/gender.py
Age-Gender models from https://github.com/Sklyvan/Age-Gender-Prediction
See also: converted to safetensors fp16, fp32 https://huggingface.co/wkpark/muddetailer/blob/main/models/README.md
- goto `"Settings"`->`μ DDetailer`
> support gender detection

- scripts/ddetailer.py
based on BMAB work https://github.com/portu-sim/sd-webui-bmab/blob/main/sd_bmab/processors/basic/final.py (AGPLv3)
these are filters using PIL enhancer after inpainting done. (works as `postprocess()`)
> support postprocess filters using PIL enhancer

- scripts/ddetailer.py
✔ Note: `submit*()` js functions have been modified by webui-forge and it breaks low-level compatibility of the A1111 webui.
> Gradio4 + forge

- scripts/ddetailer.py
prepare cached_c and cached_uc for forge case.
> fix for forge

- install.py
* install mmcv-2.2.0 for torch-2.2.x/2.3.x and above
* suppress mmengine warning for recent mmengine versions
> automatically patch mmcv version
